const cities = {
  Afikim: "Afikim",
  Afula: "Afula",
  Akko: "Akko",
  Ashdod: "Ashdod",
  BatYam: "Bat-Yam",
  Baram: "Baram",
  BeerShava: "Beer-Sheva",
  Caesarea: "Caesarea",
  Dan: "Dan",
  Dimona: "Dimona",
  EinDor: "Ein Dor",
  EinHarod: "Ein Harod",
  EinHod: "Ein Hod",
  EinShemer: "Ein Shemer",
  EmekHefer: "Emek Hefer",
  Golan: "Golan",
  Haifa: "Haifa",
  Hedera: "Hedera",
  Herzliya: "Herzliya",
  Holon: "Holon",
  Jafa: "Jafa",
  Jerusalem: "Jerusalem",
  KfarSaba: "Kfar Saba",
  KfarGiladi: "Kfar Giladi",
  KibbutzYifat: "Kibbutz Yifat",
  Kineret: "Kineret",
  KiryatAta: "Kiryat Ata",
  KiryatShmona: "Kiryat Shmona",
  KiryatTivon: "Kiryat Tivon",
  Lahav: "Lahav",
  Letron: "Letron",
  LohameiHaGeta: "Lohamei HaGeta",
  MaaleAdumim: "Maale Adumim",
  MazkertBatya: "Mazkert Batya",
  Migdal: "Migdal",
  Nahriya: "Nahriya",
  NirDavid: "Nir David",
  NirGalim: "Nir Galim",
  OrYehuda: "Or Yehuda",
  PetahTikva: "Petah Tikva",
  Raham: "Raham",
  RamatGan: "Ramat Gan",
  Ramla: "Ramla",
  Rehovot: "Rehovot",
  RishonLeZion: "Rishon Le-Zion",
  SdeBoker: "Sde Boker",
  Shtolim: "Shtolim",
  TelAviv: "Tel-Aviv",
  TelHai: "TelHai",
  TelYitzhak: "Tel Yitzhak",
  YadMordechai: "Yad Mordechai",
  Yiftah: "Yiftah",
  Yokneam: "Yokneam",
  Zefat: "Zefat",
  ZichronYaakov: "Zichron Yaakov",
};

const categories = {
  Archaeology: "Archaeology",
  Art: "Art",
  Children: "Children",
  Culture: "Culture",
  Gallery: "Gallery",
  Geological: "Geological",
  History: "History",
  Holocaust: "Holocaust",
  IDF: "IDF",
  Legacy: "Legacy",
  Music: "Music",
  Nature: "Nature",
  Science: "Science",
};

const areas = {
  Center: "Center",
  North: "North",
  South: "South",
};

const iconOnMap = {
  Archaeology: "./icons/iconArchaeology.png",
  Art: "./icons/iconArt.png",
  Children: "./icons/iconChildren.png",
  Culture: "./icons/iconCulture.png",
  Gallery: "./icons/iconsGallery.png",
  Geological: "./icons/iconGeological.png",
  History: "./icons/iconHistory.png",
  Holocaust: "./icons/iconStarOfDavid.png",
  IDF: "./icons/iconIDF.png",
  Legacy: "./icons/iconLegacy.png",
  Music: "./icons/iconMusic.png",
  Nature: "./icons/iconNature.png",
  Science: "./icons/iconScience.png",
};

const museums = [
  {
    name: "Rishon Lezion Museum",
    city: cities.RishonLeZion,
    position: { lat: 31.96567782722123, lng: 34.80739408344208 },
    website: "http://rlzm.co.il/",
    phone: "039598862",
    area: areas.Center,
    category: categories.History,
    rating: 2,
    price: 55,
    openAtWeekends: true,
    discription:
      "And Zion Rishon-Lezion, which presents the history of Rishon-Lezion, is housed in buildings from the beginning of the colony and is located in the entire historical complex of Rishon-Lezion. The entrance is from the founders' square, the place of the foundation of the colony.",
    image: "./images/rishon_lezion_museum.jpg",
  },
  {
    name: "Design Museum Holon",
    city: cities.Holon,
    position: { lat: 32.0128798761661, lng: 34.77740342205919 },
    website: "http://www.dmh.org.il/",
    phone: "0732151515",
    area: areas.Center,
    category: categories.Children,
    rating: 4,
    price: 80,
    openAtWeekends: true,
    discription:
      "The Holon Design Museum opened its doors in March 2010 and soon established itself as one of the world's leading museums for design and contemporary culture.",
    image: "./images/design_museum_holon.jpg",
  },
  {
    name: "Caruso Science Park",
    city: cities.BeerShava,
    position: { lat: 31.241613300537797, lng: 34.78593690174714 },
    website: "http://www.sci-park.co.il/",
    phone: "08-6252600",
    area: areas.South,
    category: categories.Science,
    rating: 4.5,
    price: 150,
    openAtWeekends: true,
    discription:
      "Carso Science Park is a science museum located in Be'er Sheva and was established by the Rashi Foundation, the Municipality of Be'er Sheva and the Ministry of Education in cooperation with the Lottery and the Carso family.",
    image: "./images/caruso_science_park.jpg",
  },
  {
    name: "Footprints in the valley",
    city: cities.NirDavid,
    position: { lat: 32.50456561754125, lng: 35.450696666835626 },
    website: "https://www.parks.org.il/reserve-park/shlosha/",
    phone: "046581017",
    area: areas.North,
    category: categories.Archaeology,
    rating: 4.3,
    price: 39.99,
    openAtWeekends: true,
    discription:
      "​The museum is the only one of its kind in the region, with unique artifacts from the area as well as rare finds from the Mediterranean region",
    image: "./images/footprints_in_the_valley.jpg",
  },
  {
    name: "Ein Harod Art House",
    city: cities.EinHarod,
    position: { lat: 32.56118759328433, lng: 35.39318190172171 },
    website: "https://museumeinharod.org.il/",
    phone: "04-6531670",
    area: areas.North,
    category: categories.Art,
    rating: 4.6,
    price: 50,
    openAtWeekends: true,
    discription:
      "The Haim Atar Ein Harod Art Center is one of the pioneers of the great art museums in the Land of Israel",
    image: "./images/ein_harod_art_house.jpg",
  },
  {
    name: "Tel Aviv Museum of Art",
    city: cities.TelAviv,
    position: { lat: 32.077234924258114, lng: 34.78611852459399 },
    website: "https://www.tamuseum.org.il",
    phone: "03-6077020",
    area: areas.Center,
    category: categories.Art,
    rating: 4.5,
    price: 199.99,
    openAtWeekends: true,
    discription:
      "The Tel Aviv Museum of Art is one of the most important art museums in Israel. The museum operates in the heart of the Gush Dan metropolis and has been a major art and culture institution in Israel since its establishment in 1932 until today.",
    image: "./images/tel_aviv_museum_of_art.jpg",
  },
  {
    name: "Ein Dor Museum",
    city: cities.EinDor,
    position: { lat: 32.657075822234496, lng: 35.41710818565727 },
    website: "https://eindormuseum.co.il/",
    phone: "04-6770333",
    area: areas.North,
    category: categories.Archaeology,
    rating: 4.4,
    price: 0,
    openAtWeekends: true,
    discription:
      "The archaeological museum at Kibbutz Ein Dor is located in the heart of the magical landscape of the Lower Galilee and the Jezreel Valley, at the foot of Mount Tabor",
    image: "./images/ein_dor_museum.jpg",
  },
  {
    name: "Petah Tikva Museum of Art",
    city: cities.PetahTikva,
    position: { lat: 32.08517530457248, lng: 34.87246989970905 },
    website: "http://www.petachtikvamuseum.com",
    phone: "03-9286300",
    area: areas.Center,
    category: categories.Art,
    rating: 4.2,
    price: 30,
    openAtWeekends: false,
    discription:
      "The Petah Tikva Art Museum is a contemporary art museum that exhibits works by Israeli and international artists in a variety of mediums: painting, sculpture, photography, video, cinema, architecture, installation and performance.",
    image: "./images/petah_tikva_museum_of_art.jpg",
  },
  {
    name: "Nahum Gutman Museum of Art",
    city: cities.TelAviv,
    position: { lat: 32.060943295366464, lng: 34.76652717476407 },
    website: "https://www.gutmanmuseum.co.il/",
    phone: "03-5161970",
    area: areas.Center,
    category: categories.Art,
    rating: 4.3,
    price: 28,
    openAtWeekends: true,
    discription:
      "The works of the Israeli artist and sculptor Nahum Gutman are displayed in a restored house from 1887.",
    image: "./images/nahum_gutman_museum_of_art.jpg",
  },
  {
    name: "Moshe Castel Museum of Art",
    city: cities.MaaleAdumim,
    position: { lat: 31.785420038228555, lng: 35.29804400873305 },
    website: "https://www.castelmuseum.co.il/",
    phone: "02-535-7000",
    area: areas.Center,
    category: categories.Art,
    rating: 4.4,
    price: 36,
    openAtWeekends: false,
    discription:
      "The Moshe Castel Art Museum is located in Maale Adumim and houses a selection of the works of the painter Moshe Castel.",
    image: "./images/moshe_castel_museum_of_art.jpg",
  },
  {
    name: "Mane-Katz Museum",
    city: cities.Haifa,
    position: { lat: 32.80787804928394, lng: 34.98709864061129 },
    website: "https://www.mkm.org.il",
    phone: "04-6030800",
    area: areas.North,
    category: categories.Art,
    rating: 4.2,
    price: 40,
    openAtWeekends: false,
    discription:
      "The Mane-Katz Museum is an art museum in the city of Haifa, dedicated to the work of the painter Mane Katz",
    image: "./images/mane-katz_museum.jpg",
  },
  {
    name: "Kfar Saba Museum",
    city: cities.KfarSaba,
    position: { lat: 32.17767711532906, lng: 34.90609759938647 },
    website: "https://kfar-saba-museum.org",
    phone: "09-7640868",
    area: areas.Center,
    category: categories.Archaeology,
    rating: 4.4,
    price: 45,
    openAtWeekends: false,
    discription:
      "The Kfar Saba Museum is a museum located in Kiryat Sapir on Jerusalem Street in Kfar Saba. The museum includes a variety of exhibits and rotating exhibitions on the past of Kfar Saba and focuses in particular on archeology",
    image: "./images/kfar_saba_museum.jpg",
  },
  {
    name: "Israel Museum Jerusalem",
    city: cities.Jerusalem,
    position: { lat: 31.772127646064845, lng: 35.2040710342284 },
    website: "https://www.imj.org.il/",
    phone: "026708811",
    area: areas.Center,
    category: categories.Archaeology,
    rating: 4.7,
    price: 54,
    openAtWeekends: true,
    discription:
      "A museum of art and archeology with prehistoric and modern collections, including the Dead Sea Scrolls.",
    image: "./images/israel_museum_jerusalem.jpg",
  },
  {
    name: "Yanko-Dada Museum",
    city: cities.EinHod,
    position: { lat: 32.701772671748756, lng: 34.979996199999995 },
    website: "http://www.jancodada.co.il/",
    phone: "049842350",
    area: areas.North,
    category: categories.Art,
    rating: 4.2,
    price: 54,
    openAtWeekends: true,
    discription:
      "The Yanko Dada Museum is located in the artists' village of Ein Hod. The museum was established in 1983 by a group of friends of the artist Marcel Janko, one of the founders of the global Dada movement who was among the founders of the village.",
    image: "./images/yanko-dada_museum.jpg",
  },
  {
    name: "Yad Mordechai Museum",
    city: cities.YadMordechai,
    position: { lat: 31.589835586816772, lng: 34.55736771810923 },
    website: "http://www.y-m-museum.co.il/",
    phone: "none",
    area: areas.South,
    category: categories.Holocaust,
    rating: 4.6,
    price: 50,
    openAtWeekends: false,
    discription:
      "The Beacon of Revival museum in Kibbutz Yad Mordechai tells the story of the Jewish people in the tragic and dramatic decade of the Holocaust and the Revival and invites you on a journey that begins with life in occupied Europe and continues to the fateful battles of 1958 on the land of the kibbutz on the way to the establishment of the state, and from there to this time - of Haim Bezal The Qassams in the Gaza Strip.",
    image: "./images/yad_mordechai_museum.jpg",
  },
  {
    name: "Tikotin Museum of Japanese Art",
    city: cities.Haifa,
    position: { lat: 32.80926924210541, lng: 34.9852799286092 },
    website: "http://www.tmja.org.il/",
    phone: "046030800",
    area: areas.North,
    category: categories.Art,
    rating: 4.3,
    price: 35,
    openAtWeekends: true,
    discription:
      "Exhibitions of textiles, ceramics and samurai swords, as well as tea ceremonies, in an impressive museum down the hill.",
    image: "./images/tikotin_museum_of_japanese_art.jpg",
  },
  {
    name: "Hetzer-Rashinom Museum",
    city: cities.EinShemer,
    position: { lat: 32.46398995223007, lng: 35.00406868617302 },
    website: "http://www.courtyard.co.il/",
    phone: "046374327",
    area: areas.North,
    category: categories.History,
    rating: 4.4,
    price: 55,
    openAtWeekends: true,
    discription:
      "The yard of the first ones consists of several buildings that include original buildings and reconstructions of buildings of the original yard of Kibbutz Ein Shemer",
    image: "./images/hetzer_rashinom_museum.jpg",
  },
  {
    name: "Tel-Hai Court Museum",
    city: cities.KiryatShmona,
    position: { lat: 33.23576790465608, lng: 35.57817037116368 },
    website: "http://www.telhai.ac.il/",
    phone: "048181855",
    area: areas.North,
    category: categories.History,
    rating: 4.2,
    price: 60,
    openAtWeekends: true,
    discription:
      "In the summer of 1907 an agricultural farm was established at this spot, which became kibbutz Tel Hai following the First World War.",
    image: "./images/tel_hai_court_museum.jpg",
  },
  {
    name: "Old Yishuv Court Museum",
    city: cities.Jerusalem,
    position: { lat: 31.77525296472731, lng: 35.23027768680273 },
    website: "http://www.oyc.co.il/",
    phone: "026276319",
    area: areas.Center,
    category: categories.History,
    rating: 4.6,
    price: 60,
    openAtWeekends: false,
    discription:
      "The life of the residents from the period of the old settlement is illustrated through objects displayed in this ancient house.",
    image: "./images/old_yishuv_court_museum.jpg",
  },
  {
    name: "Haifa Museum of Art",
    city: cities.Haifa,
    position: { lat: 32.81505681195554, lng: 34.99255617853355 },
    website: "http://www.hma.org.il/",
    phone: "046030800",
    area: areas.North,
    category: categories.Art,
    rating: 4.2,
    price: 49.99,
    openAtWeekends: true,
    discription:
      "A collection of modern works by Israeli and international artists, such as Marc Chagall and Hanna Orloff.",
    image: "./images/haifa_museum_of_art.jpg",
  },
  {
    name: "Wilfrid Israel Museum of Oriental Art and Knowledge",
    city: cities.Yokneam,
    position: { lat: 32.64444368101217, lng: 35.117763843957505 },
    website: "http://www.wilfrid.org.il/",
    phone: "049899566",
    area: areas.North,
    category: categories.Art,
    rating: 4.4,
    price: 74.99,
    openAtWeekends: true,
    discription:
      "A collection of modern works by Israeli and international artists, such as Marc Chagall and Hanna Orloff.",
    image: "./images/wilfrid_israel_museum_of_oriental_art_and_knowledge.jpg",
  },
  {
    name: "Yarmochit Culture Museum",
    city: cities.Golan,
    position: { lat: 32.68577505184407, lng: 35.60554937004695 },
    website: "http://www.myc.org.il/",
    phone: "0527994344",
    area: areas.North,
    category: categories.Culture,
    rating: 4.6,
    price: 20,
    openAtWeekends: true,
    discription:
      "The Museum of Yarmukian Culture at kibbutz Shaar Hagolan is well known all over the world for the number and quality of items on its display.",
    image: "./images/yarmochit_culture_museum.jpg",
  },
  {
    name: "Herzliya Museum of Contemporary Art",
    city: cities.Herzliya,
    position: { lat: 32.162251004811495, lng: 34.844144580505244 },
    website: "http://www.herzliyamuseum.co.il/",
    phone: "099551011",
    area: areas.Center,
    category: categories.Art,
    rating: 4.5,
    price: 30,
    openAtWeekends: true,
    discription:
      "The beginnings of the Herzliya Museum in a collection of paintings from the eighteenth century to the twentieth century, which were donated to the municipality of Herzliya by resident Eugene de Villa in the early sixties of the twentieth century.",
    image: "./images/herzliya_museum_of_contemporary_art.jpg",
  },
  {
    name: "Hermann Struck Museum",
    city: cities.Haifa,
    position: { lat: 32.80469081661603, lng: 35.00051429977298 },
    website: "http://www.shm.org.il",
    phone: "046030800",
    area: areas.North,
    category: categories.Art,
    rating: 4.2,
    price: 50,
    openAtWeekends: true,
    discription: "The museum presents the works of Hermann Struck.",
    image: "./images/hermann_struck_museum.jpg",
  },
  {
    name: "The Valley Museum in Kibbutz Yifat",
    city: cities.KibbutzYifat,
    position: { lat: 32.673591544954284, lng: 35.22591775025414 },
    website: "http://www.pioneers.co.il/",
    phone: "046548974",
    area: areas.North,
    category: categories.Art,
    rating: 4.4,
    price: 0,
    openAtWeekends: true,
    discription:
      "The Oded Artzi Museum of the Valley in Kibbutz Yifat presents and tells the wonderful story of the settlers of the valley, the pioneers who settled there in the 1920s, until the establishment of the state.",
    image: "./images/the_valley_museum_in_kibbutz_yifat.jpg",
  },
  {
    name: "Haifa City Museum",
    city: cities.Haifa,
    position: { lat: 32.822188313059755, lng: 34.99217663046321 },
    website: "http://www.hcm.org.il",
    phone: "046030800",
    area: areas.North,
    category: categories.Art,
    rating: 4.0,
    price: 25,
    openAtWeekends: true,
    discription:
      "Exhibitions that are mainly dedicated to Haifa's cultural past and are presented in a templar structure.",
    image: "./images/haifa_city_museum.jpg",
  },
  {
    name: "The Colony Museum",
    city: cities.MazkertBatya,
    position: { lat: 31.854290383024882, lng: 34.8383076709306 },
    website: "http://www.mazkeret.org/museum/",
    phone: "089349525",
    area: areas.Center,
    category: categories.Art,
    rating: 4.4,
    price: 40,
    openAtWeekends: true,
    discription:
      "Exhibitions that are mainly dedicated to Haifa's cultural past and are presented in a templar structure.",
    image: "./images/the_colony_museum.jpg",
  },
  {
    name: "Science Museum",
    city: cities.Jerusalem,
    position: { lat: 31.77832194073246, lng: 35.20048339082342 },
    website: "http://mada.org.il/",
    phone: "026544888",
    area: areas.Center,
    category: categories.Science,
    rating: 4.4,
    price: 50,
    openAtWeekends: true,
    discription:
      "A science museum for children with interactive exhibits, workshops and performances.",
    image: "./images/science_museum_jerusalem.jpg",
  },
  {
    name: "Shlomo Hall Museum of Jewish Art",
    city: cities.Jerusalem,
    position: { lat: 31.779330020094136, lng: 35.21584583048258 },
    website:
      "https://makom.hamoreshet.org.il/landmark/heichal-shlomo-museum-of-jewish-art-jerusalem/",
    phone: "NONE",
    area: areas.Center,
    category: categories.Art,
    rating: 4.1,
    price: 45,
    openAtWeekends: false,
    discription:
      "The heritage site and the charming museum in Solomon's Temple connect you to the unparalleled Jewish heritage.",
    image: "./images/shlomo_hall_museum_of_jewish_art.jpg",
  },
  {
    name: "Hecht Museum",
    city: cities.Haifa,
    position: { lat: 32.76319423691253, lng: 35.0180348727915 },
    website: "http://mushecht.haifa.ac.il/",
    phone: "048240450",
    area: areas.North,
    category: categories.Art,
    rating: 4.7,
    price: 70,
    openAtWeekends: true,
    discription:
      "Archaeological remains from the Canaanite period to the Byzantine period, handicrafts and art objects from the 19th century.",
    image: "./images/hecht_museum.jpg",
  },
  {
    name: "The Prehistoric Man Museum",
    city: cities.KiryatShmona,
    position: { lat: 33.23813057648371, lng: 35.60866756083145 },
    website: "http://ugmp.co.il/",
    phone: "046954628",
    area: areas.North,
    category: categories.History,
    rating: 4.6,
    price: 25,
    openAtWeekends: true,
    discription:
      "The Museum of Ancient Man offers a variety of its visitors a unique opportunity to be exposed to the way of life of man in prehistoric times.",
    image: "./images/the_prehistoric_man_museum.jpg",
  },
  {
    name: "Museum of Man and the Environment",
    city: cities.PetahTikva,
    position: { lat: 32.08823625191142, lng: 34.87316730505436 },
    website: "http://www.adamsviva-pt.org.il/",
    phone: "039286900",
    area: areas.Center,
    category: categories.Science,
    rating: 4.4,
    price: 25,
    openAtWeekends: true,
    discription:
      "The Museum of Man and the Environment is an officially recognized museum by the Ministry of Culture, specializing in the fields of anatomy and physiology of the human body and the subject of promoting health, all of this alongside environmental issues and the interrelationship between man and his environment.",
    image: "./images/museum_of_man_and_the_environment.jpg",
  },
  {
    name: "Rubin Museum",
    city: cities.TelAviv,
    position: { lat: 32.07205358977933, lng: 34.77073883047711 },
    website: "http://www.rubinmuseum.org.il/",
    phone: "035255961",
    area: areas.Center,
    category: categories.Art,
    rating: 4.4,
    price: 30,
    openAtWeekends: true,
    discription:
      "A museum dedicated to the life and work of the pioneering Israeli painter Reuven Rubin, and located in the place where his home was.",
    image: "./images/rubin_museum.jpg",
  },
  {
    name: "Bar-David Museum of Art and Judaica",
    city: cities.Raham,
    position: { lat: 33.05946497515694, lng: 35.43156691110132 },
    website: "http://www.bardavid-museum.org.il/",
    phone: "046988295",
    area: areas.North,
    category: categories.Art,
    rating: 4.4,
    price: 26,
    openAtWeekends: true,
    discription:
      "A museum dedicated to the life and work of the pioneering Israeli painter Reuven Rubin, and located in the place where his home was.",
    image: "./images/bar-david_museum_of_art_and_judaica.jpg",
  },
  {
    name: "Beit Theresienstadt",
    city: cities.EmekHefer,
    position: { lat: 32.397332263014626, lng: 34.932713152399586 },
    website: "http://www.bterezin.org.il/",
    phone: "046369515",
    area: areas.Center,
    category: categories.Culture,
    rating: 4.5,
    price: 25,
    openAtWeekends: false,
    discription:
      "Beit Terezin was established in Kibbutz Givat Haim Ihud and has a historical museum, exhibition rooms, an archive, an index of the names of prisoners who passed through Terezinstadt and a library.",
    image: "./images/beit_theresienstadt.jpg",
  },
  {
    name: "The sea museum and its entirety",
    city: cities.RishonLeZion,
    position: { lat: 31.93421477614452, lng: 34.70384913047981 },
    website: "https://www.betmiriam.co.il/",
    phone: "039538281",
    area: areas.Center,
    category: categories.Archaeology,
    rating: 4.3,
    price: 40,
    openAtWeekends: false,
    discription:
      "The museum aims to be a leading center in the field of marine archeology and ecology and to provide an educational experiential space that exposes its visitors to the importance of the marine environment and its protection.",
    image: "./images/the_sea_museum_and_its_entirety.jpg",
  },
  {
    name: "Beit Hameiri",
    city: cities.Zefat,
    position: { lat: 31.93421477614452, lng: 34.70384913047981 },
    website: "NONE",
    phone: "NONE",
    area: areas.North,
    category: categories.History,
    rating: 4.3,
    price: 40,
    openAtWeekends: false,
    discription:
      "The museum aims to be a leading center in the field of marine archeology and ecology and to provide an educational experiential space that exposes its visitors to the importance of the marine environment and its protection.",
    image: "./images/beit_hameiri.jpg",
  },
  {
    name: "ANU Museum of the Jewish People",
    city: cities.TelAviv,
    position: { lat: 32.11383237208551, lng: 34.8052684150115 },
    website: "https://www.anumuseum.org.il/he/",
    phone: "035008080",
    area: areas.Center,
    category: categories.Culture,
    rating: 4.5,
    price: 52,
    openAtWeekends: true,
    discription:
      "The Museum of the Jewish People is a global institution that tells about one multi-faceted, rich and multi-layered culture",
    image: "./images/anu_museum_of_the_jewish_people.jpg",
  },
  {
    name: "Ashdod Museum of Art",
    city: cities.Ashdod,
    position: { lat: 31.792055187684777, lng: 34.63682422306559 },
    website: "NONE",
    phone: "088545180",
    area: areas.Center,
    category: categories.Art,
    rating: 4.2,
    price: 0,
    openAtWeekends: true,
    discription: "NONE",
    image: "./images/ashdod_museum_of_art.jpg",
  },
  {
    name: "Uri & Rami Nehoshtan Museum ",
    city: cities.Afikim,
    position: { lat: 32.660925976344764, lng: 35.58264103171727 },
    website: "http://www.uri-rami-museum.co.il/",
    phone: "046757737",
    area: areas.North,
    category: categories.Art,
    rating: 4.2,
    price: 0,
    openAtWeekends: true,
    discription:
      "The Beit Uri Vermi Nehushtan Museum is a contemporary art museum located south of the Sea of Galilee, in Kibbutz Ashdot Ya'akov Mauchad. The museum presents changing exhibitions of artists working in Israel and abroad as well as exhibitions from the museum's collection",
    image: "./images/uri_&_rami_nehoshtan_museum.jpg",
  },
  {
    name: "Khan Museum ",
    city: cities.Hedera,
    position: { lat: 32.437024209879795, lng: 34.923670982800516 },
    website: "http://www.museum-khanhadera.org.il/",
    phone: "046324562",
    area: areas.North,
    category: categories.History,
    rating: 4.5,
    price: 30,
    openAtWeekends: false,
    discription:
      "The Khan Museum Hadera (AR) is located in the national site of the Khan of Hadera, in the historical center of the city. The impressive kurkar building was originally an Ottoman agricultural farm house from the mid-nineteenth century.",
    image: "./images/khan_museum.jpg",
  },
  {
    name: "Bible Lands Museum Jerusalem ",
    city: cities.Jerusalem,
    position: { lat: 32.437024209879795, lng: 34.923670982800516 },
    website: "http://www.blmj.org/",
    phone: "025611066",
    area: areas.Center,
    category: categories.History,
    rating: 4.4,
    price: 40,
    openAtWeekends: false,
    discription:
      "A contemporary museum with a collection of antiquities and historical displays from the time of the Bible and the lands of the Bible.",
    image: "./images/bible_lands_museum_jerusalem.jpg",
  },
  {
    name: "Madatech",
    city: cities.Haifa,
    position: { lat: 32.810351415465796, lng: 34.9963534304634 },
    website: "https://www.madatech.org.il/",
    phone: "048614444",
    area: areas.North,
    category: categories.Science,
    rating: 4.5,
    price: 80,
    openAtWeekends: true,
    discription:
      "Over 600 exhibits, in a building that used to be the first academic institution in Israel and was converted into a science museum for the whole family.",
    image: "./images/madatech.jpg",
  },
  {
    name: "Museum of Islamic Art",
    city: cities.Jerusalem,
    position: { lat: 31.76856170274869, lng: 35.2131258016465 },
    website: "https://www.tod.org.il/",
    phone: "026265333",
    area: areas.Center,
    category: categories.Culture,
    rating: 4.6,
    price: 44,
    openAtWeekends: true,
    discription:
      "TA medieval citadel on the site of fortifications, some of which were built about 2,000 years ago, and a museum of the history of Jerusalem.",
    image: "./images/museum_of_islamic_art.jpg",
  },
  {
    name: "Tower of David",
    city: cities.Jerusalem,
    position: { lat: 31.77633483990049, lng: 35.22844518815523 },
    website: "https://www.tod.org.il/",
    phone: "026265333",
    area: areas.Center,
    category: categories.History,
    rating: 4.6,
    price: 38,
    openAtWeekends: true,
    discription:
      "A medieval citadel on the site of fortifications, some of which were built about 2,000 years ago, and a museum of the history of Jerusalem.",
    image: "./images/tower_of_david.jpg",
  },
  {
    name: "The Mizgaga Museum",
    city: cities.Shtolim,
    position: { lat: 32.612741334458306, lng: 34.91825686525 },
    website: "http://www.mizgaga.com/",
    phone: "046390950",
    area: areas.North,
    category: categories.History,
    rating: 4.6,
    price: 30,
    openAtWeekends: true,
    discription:
      "The actual glass factory The Mazgaga Museum is housed in an impressive two-story stone building, in the heart of Kibbutz Nachsholim on the Carmel coast. The construction of the glasshouse was initiated by Baron Edmond de Rothschild in 1891 as a factory for glass bottles for the Rishon Lezion and Zichron Yaakov wineries.",
    image: "./images/the_mizgaga_museum.jpg",
  },
  {
    name: "Museum of Israeli Art",
    city: cities.RamatGan,
    position: { lat: 32.09453570283377, lng: 34.81924067280406 },
    website: "http://www.rgma.org.il/",
    phone: "037521876",
    area: areas.Center,
    category: categories.Art,
    rating: 4.1,
    price: 0,
    openAtWeekends: false,
    discription: "Colse.",
    image: "./images/museum_of_israeli_art.jpg",
  },
  {
    name: "The open museum Tefen",
    city: cities.Nahriya,
    position: { lat: 32.98089066008139, lng: 35.275174363612386 },
    website: "NONE",
    phone: "049109611",
    area: areas.North,
    category: categories.Art,
    rating: 4.2,
    price: 0,
    openAtWeekends: false,
    discription: "Colse.",
    image: "./images/the_open_museum_tefen.jpg",
  },
  {
    name: "Israeli Cartoon Museum",
    city: cities.Holon,
    position: { lat: 32.01523319411564, lng: 34.77074142883632 },
    website: "https://cartoon.org.il/",
    phone: "036521849",
    area: areas.Center,
    category: categories.Art,
    rating: 4.1,
    price: 15,
    openAtWeekends: true,
    discription:
      "A museum exposes visitors to the art of caricature on its layers, connections and qualities, with the aim of promoting the understanding and recognition of the existence and necessity of caricature as a critical tool in society and comics as a literary genre with depth.",
    image: "./images/israeli_cartoon_museum.jpg",
  },
  {
    name: "National Maritime Museum",
    city: cities.Haifa,
    position: { lat: 32.82896678463882, lng: 34.97235022883631 },
    website: "http://www.nmm.org.il/%D7%A6%D7%95%D7%A8_%D7%A7%D7%A9%D7%A8",
    phone: "046030800",
    area: areas.North,
    category: categories.Archaeology,
    rating: 4.3,
    price: 35,
    openAtWeekends: true,
    discription:
      "The National Maritime Museum in Haifa presents the history of shipping in the Mediterranean basin and the maritime story of the city of Haifa. The museum exhibits over 5000 years of maritime history and archaeology",
    image: "./images/national_maritime_museum.jpg",
  },
  {
    name: "Shoham Unit",
    city: cities.Rehovot,
    position: { lat: 31.91038019614534, lng: 34.81317756117069 },
    website: "http://davidson.weizmann.ac.il/",
    phone: "089378300",
    area: areas.Center,
    category: categories.Archaeology,
    rating: 4.0,
    price: 0,
    openAtWeekends: true,
    discription: "The science park is being renewed and is under construction",
    image: "./images/shoham_unit.jpg",
  },
  {
    name: "Yigal Allon Centre",
    city: cities.Migdal,
    position: { lat: 32.845098391043955, lng: 35.52523105016332 },
    website: "http://www.yigal-allon-centre.org.il/",
    phone: "046727700",
    area: areas.North,
    category: categories.History,
    rating: 4.5,
    price: 42,
    openAtWeekends: true,
    discription:
      "Beit Yigal Alon was established in 1986 as part of the association to commemorate the legacy of Yigal Alon",
    image: "./images/yigal_allon_centre.jpg",
  },
  {
    name: "Sturman Museum",
    city: cities.Afula,
    position: { lat: 32.56113106176246, lng: 35.39532580546169 },
    website: "http://www.beit-shturman.co.il/",
    phone: "046486328",
    area: areas.North,
    category: categories.History,
    rating: 4.2,
    price: 40,
    openAtWeekends: true,
    discription:
      "Beit Sturman is the first settlement museum established in the Land of Israel. The museum is named after Haim Sturman - the guard, member of the Haganah and a role model for heroism and love for the Land of Israel.",
    image: "./images/sturman_museum.jpg",
  },
  {
    name: "Beit Ussishkin Nature Museum",
    city: cities.Dan,
    position: { lat: 33.24235110383241, lng: 35.65536598731179 },
    website: "http://museum.teva.org.il/",
    phone: "046941704",
    area: areas.North,
    category: categories.Nature,
    rating: 4.4,
    price: 25,
    openAtWeekends: true,
    discription:
      "Beit Osishkin Nature Museum of the Society for the Protection of Nature Kibbutz Dan. Museum of Nature and History",
    image: "./images/beit_ussishkin_nature_museum.jpg",
  },
  {
    name: "Beit Aaronsohn – Nili Museum",
    city: cities.ZichronYaakov,
    position: { lat: 32.572391800000005, lng: 34.95473114232737 },
    website: "http://www.nili-museum.org.il/",
    phone: "046390120",
    area: areas.North,
    category: categories.History,
    rating: 4.4,
    price: 36,
    openAtWeekends: true,
    discription:
      "Yat Ahernson The NIL Museum was established in Zichron Ya'akov in 1956 next to the Ahernson family's house which was built in 1884 and was the center of activity for the NIL underground.",
    image: "./images/beit_aaronsohn_–_nili_museum.jpg",
  },
  {
    name: "Bank of Israel Visitor Center",
    city: cities.TelAviv,
    position: { lat: 32.06246390319042, lng: 34.77213575419414 },
    website:
      "https://www.boi.org.il/en/Education/VisitorsCenter/Pages/Default.aspx",
    phone: "035640781",
    area: areas.Center,
    category: categories.History,
    rating: 4.5,
    price: 0,
    openAtWeekends: false,
    discription: "None",
    image: "./images/bank_of_israel_visitor_center.jpg",
  },
  {
    name: "Eretz Israel Museum",
    city: cities.TelAviv,
    position: { lat: 32.103226235360076, lng: 34.79631688931869 },
    website: "http://www.eretzmuseum.org.il/",
    phone: "036415244",
    area: areas.Center,
    category: categories.History,
    rating: 4.4,
    price: 49,
    openAtWeekends: true,
    discription:
      "A large museum with displays in halls and open spaces. The museum presents the culture of Israel and its history, and also includes a planetarium and a garden.",
    image: "./images/eretz_israel_museum.jpg",
  },
  {
    name: "Eno Museum (former Diaspora House)",
    city: cities.TelAviv,
    position: { lat: 32.11382472704149, lng: 34.805255368088886 },
    website: "https://www.anumuseum.org.il/he/",
    phone: "035008080",
    area: areas.Center,
    category: categories.History,
    rating: 4.5,
    price: 52,
    openAtWeekends: true,
    discription:
      "The museum presents exhibits on the history of Jewish culture and faith up to the present day.",
    image: "./images/eno_museum.jpg",
  },
  {
    name: "Mashoah Museum",
    city: cities.TelYitzhak,
    position: { lat: 32.25493847959379, lng: 34.869763690329314 },
    website: "http://www.massuah.org.il/",
    phone: "098999997",
    area: areas.Center,
    category: categories.Holocaust,
    rating: 4.3,
    price: 0,
    openAtWeekends: true,
    discription:
      "The International Institute for Holocaust Studies is an information preservation institution that includes a public archive and a central school for the teaching of the Holocaust, designed to stimulate discourse on its meaning for contemporary society and culture.",
    image: "./images/mashoah_museum.jpg",
  },
  {
    name: "The Ziva Belkin Geological Museum",
    city: cities.RamatHasharon,
    position: { lat: 32.146752446606406, lng: 34.843163886678774 },
    website: "None",
    phone: "None",
    area: areas.Center,
    category: categories.Geological,
    rating: 4.3,
    price: 0,
    openAtWeekends: false,
    discription: "None",
    image: "./images/the_ziva_belkin_geological_museum.jpg",
  },
  {
    name: "Beit Krinitsi Museum of Ramat Gan History",
    city: cities.RamatGan,
    position: { lat: 32.08313354305489, lng: 34.819472569076446 },
    website: "http://beit-krinitzi.org.il/",
    phone: "036739050",
    area: areas.Center,
    category: categories.History,
    rating: 4.2,
    price: 0,
    openAtWeekends: false,
    discription:
      "The Avraham Karinitsi House is one of the first stone houses built in Ramat Gan. The house was built in 1925, on two levels (ground and basement) and was the private home of the Krinitsi family.",
    image: "./images/beit_krinitsi_museum_of_ramat_gan_history.jpg",
  },
  {
    name: "Ilana Gore Museum",
    city: cities.RamatHasharon,
    position: { lat: 32.05336249043797, lng: 34.75147014698483 },
    website: "https://www.ilanagoormuseum.org/en/",
    phone: "036837676",
    area: areas.Center,
    category: categories.Art,
    rating: 4.7,
    price: 0,
    openAtWeekends: true,
    discription:
      "An eclectic collection of the works of artist Ilana Gore, displayed in her private home housed in a historic building.",
    image: "./images/ilana_gore_museum.jpg",
  },
  {
    name: "President Chaim Weizman's house",
    city: cities.Rehovot,
    position: { lat: 31.906473768478012, lng: 34.81856422534265 },
    website: "http://www.chaimweizmann.org.il/",
    phone: "089343230",
    area: areas.Center,
    category: categories.History,
    rating: 4.7,
    price: 0,
    openAtWeekends: false,
    discription:
      "Beit Chaim Weizman was the private home of the first president of the State of Israel, Dr. Chaim Weizman, and his wife, Dr. Vera Weizman. The house is located on a hill in Rehovot, which is now part of the Weizmann Institute of Science campus.",
    image: "./images/president_chaim_weizman's_house.jpg",
  },
  {
    name: "Klor Science Garden Museum - Davidson Institute",
    city: cities.Rehovot,
    position: { lat: 31.909920488277876, lng: 34.81348146405766 },
    website: "http://davidson.weizmann.ac.il/science-garden",
    phone: "089378300",
    area: areas.Center,
    category: categories.History,
    rating: 4.5,
    price: 0,
    openAtWeekends: false,
    discription: "None",
    image: "./images/klor_science_garden_museum_-_davidson_institute.jpg",
  },
  {
    name: "Man and the Living World Museum",
    city: cities.RamatGan,
    position: { lat: 32.04776138539592, lng: 34.81620990240013 },
    website: "http://www.adamvechai.org.il/",
    phone: "None",
    area: areas.Center,
    category: categories.Science,
    rating: 4.1,
    price: 0,
    openAtWeekends: false,
    discription:
      "In the heart of the national park, next to the safari, is the Museum of Man and AnimalsA small and intimate nature museum that invites you to a family experience through all the senses.During the visit you can enjoy exhibitions, diverse nature collections, archeology and fascinating displays in an accessible and special space.Join us for family activities, study tours, events in an enriching and experiential environment",
    image: "./images/man_and_the_living_world_museum.jpg",
  },
  {
    name: "Israel Puppet center Holon",
    city: cities.Holon,
    position: { lat: 32.01008355234809, lng: 34.7673036367006 },
    website: "https://www.puppetcenter.co.il/",
    phone: "036516848",
    area: areas.Center,
    category: categories.Culture,
    rating: 4.5,
    price: 0,
    openAtWeekends: false,
    discription:
      "The Israel Puppet Center is unique in the Middle East and the Mediterranean basin in that it has a school (teaching artistic puppetry and puppetry as a therapeutic and educational tool)",
    image: "./images/israel_puppet_center_holon.jpg",
  },
  {
    name: "Hosmasa museum",
    city: cities.Holon,
    position: { lat: 32.00751897992022, lng: 34.785081956813976 },
    website:
      "https://museum.holonet.co.il/class/672/%D7%9E%D7%95%D7%96%D7%99%D7%90%D7%95%D7%9F-%D7%97%D7%95%D7%A1%D7%9E%D7%A1%D7%94",
    phone: "035050425",
    area: areas.Center,
    category: categories.History,
    rating: 4.3,
    price: 0,
    openAtWeekends: false,
    discription:
      "The Hosmasa Museum tells the story of the 'Hagana' in Holon and its surroundings during the War of Independence and the pre-statehood period. ",
    image: "./images/hosmasa_museum.jpg",
  },
  {
    name: "Yaacov Agam Museum of Art",
    city: cities.RishonLeZion,
    position: { lat: 32.00751897992022, lng: 34.785081956813976 },
    website: "http://yama.co.il/",
    phone: "035555900",
    area: areas.Center,
    category: categories.History,
    rating: 4.5,
    price: 35,
    openAtWeekends: true,
    discription:
      "The Rishon Lezion Lake Museum is accessible and offers a variety of guided toursIn Hebrew, English, Russian, Arabic and French by prior arrangement Creative workshops for children and unique cultural events. In addition, activity for companies and organizations customized and in a variety of options",
    image: "./images/yaacov_agam_museum_of_art.jpg",
  },
  {
    name: "Kfar Saba Museum",
    city: cities.Jerusalem,
    position: { lat: 32.17766793492223, lng: 34.90609447035665 },
    website: "http://www.kfar-saba-museum.org/",
    phone: "097640868",
    area: areas.Center,
    category: categories.Archaeology,
    rating: 4.4,
    price: 40,
    openAtWeekends: true,
    discription:
      "About Kfar Saba Museum The Kfar Saba Museum was founded in 1980 (2007) on the initiative of the mayor Ze'ev Geller and the archaeologist, resident of Kfar Saba, Dr. Eitan Ayalon as an archaeological museum for the history of the city of Kfar Saba.",
    image: "./images/kfar_saba_museum.jpg",
  },
  {
    name: "Tel Hai Court Museum",
    city: cities.TelHai,
    position: { lat: 33.233700583761646, lng: 35.577324154866524 },
    website: "http://www.hatser-telhai.org.il/",
    phone: "046951333",
    area: areas.North,
    category: categories.History,
    rating: 4.4,
    price: 0,
    openAtWeekends: true,
    discription:
      "At the foot of the Upper Galilee Mountains, at the top of a hill overlooking the spectacular scenery of the Hula Valley, lies Tel-Hai Court.The small yard built of rough basalt stones was a value and a concept that illuminates the paths of our lives to this day.",
    image: "./images/tel_hai_court_museum.jpg",
  },
  {
    name: "Ghetto Fighters' House Lohamei HaGeta'ot",
    city: cities.LohameiHaGeta,
    position: { lat: 32.96058874511157, lng: 35.09536614697467 },
    website: "https://www.gfh.org.il/",
    phone: "049958080",
    area: areas.North,
    category: categories.Holocaust,
    rating: 4.7,
    price: 0,
    openAtWeekends: false,
    discription:
      "Holocaust and Revolt Heritage Museum opened in 1949, with exhibitions and guided tours.",
    image: "./images/ghetto_fighters'_house_lohamei_hageta'ot.jpg",
  },
  {
    name: "Memorial Center in Kiryat Tivon",
    city: cities.KiryatTivon,
    position: { lat: 32.71239280585225, lng: 35.12668272815071 },
    website: "http://www.tivon-lib.co.il/",
    phone: "049835506",
    area: areas.North,
    category: categories.Culture,
    rating: 4.5,
    price: 0,
    openAtWeekends: false,
    discription:
      "The Israeli Art Gallery in the Commemoration Center is a museum exhibition space, where solo and group exhibitions of first-rate artists in the art field in Israel are presented.",
    image: "./images/memorial_center_in_kiryat_tivon.jpg",
  },
  {
    name: "Beit Ussishkin Nature Museum",
    city: cities.Dan,
    position: { lat: 33.241166741064255, lng: 35.65560323021387 },
    website: "http://museum.teva.org.il/",
    phone: "046941704",
    area: areas.North,
    category: categories.Nature,
    rating: 4.4,
    price: 0,
    openAtWeekends: false,
    discription:
      "A museum displays and collections from the variety of habitats and landscapes of the northern region of Israel, the Golan and the Hermon, and a special exhibition dedicated to human life in the region during the biblical period, based on findings uncovered in the archaeological excavations conducted in Tel Dan.",
    image: "./images/beit_ussishkin_nature_museum.jpg",
  },
  {
    name: "Mishkan Museum of Art",
    city: cities.EinHarod,
    position: { lat: 32.561102675125625, lng: 35.3931860559825 },
    website: "http://www.museumeinharod.org.il/",
    phone: "046486038",
    area: areas.North,
    category: categories.Art,
    rating: 4.6,
    price: 0,
    openAtWeekends: true,
    discription:
      "The leading and oldest museum in the north, presents art exhibitions of the best artists in Israel and the world. The museum has one of the largest collections of Jewish artists from the late 19th and early 20th centuries",
    image: "./images/mishkan_museum_of_art.jpg",
  },
  {
    name: "HaReut Museum",
    city: cities.Yiftah,
    position: { lat: 33.11643842026632, lng: 35.556849523235556 },
    website: "http://www.reut-museum.co.il/",
    phone: "046432810",
    area: areas.North,
    category: categories.History,
    rating: 4.7,
    price: 24,
    openAtWeekends: true,
    discription:
      "The museum describes the phases of the construction of the Police Citadel by the British, the battles of the Upper Galilee at the beginning of the War of Independence, the three battles and their participants, most of them members of the 9 kashruts of the Palmach, and a large space is dedicated to the commemoration of the fallen.",
    image: "./images/hareut_museum.jpg",
  },
  {
    name: "Ralli Museum, Caesarea",
    city: cities.Caesarea,
    position: { lat: 32.51440390810082, lng: 34.90734334803502 },
    website: "http://www.rallimuseums.com/146",
    phone: "046261013",
    area: areas.North,
    category: categories.Art,
    rating: 4.8,
    price: 0,
    openAtWeekends: true,
    discription:
      "Experience contemporary Latin American art along with surrealist and classical art The Harry Recanati Foundation is a private non-profit institution. Its main purpose is to present and spread the quality of contemporary Latin American art, through Raleigh museums.",
    image: "./images/ralli_museum_caesarea.jpg",
  },
  {
    name: "Kinneret Courtyard",
    city: cities.Kineret,
    position: { lat: 32.721792448688724, lng: 35.56756733284491 },
    website: "http://www.shimur.org/Kinneret",
    phone: "046709117",
    area: areas.North,
    category: categories.History,
    rating: 4.4,
    price: 25,
    openAtWeekends: true,
    discription:
      "A place that operates a visitor and training center for the heritage of the second immigration and the settlement in the Jordan Valley. The tour of the site includes the courtyard buildings, the dining room, the barn, the maiden farm, the khan and a video about Rachel the poet.",
    image: "./images/kinneret_courtyard.jpg",
  },
  {
    name: "Caesarea Antiquity Museum",
    city: cities.Caesarea,
    position: { lat: 32.49144017988814, lng: 34.89075933871133 },
    website: "http://www.caesareamuseum.com/",
    phone: "046364548",
    area: areas.North,
    category: categories.Archaeology,
    rating: 4.5,
    price: 30,
    openAtWeekends: true,
    discription:
      "The museum exhibits archaeologists who were discovered in the area by kibbutz members and expeditions that excavated in Caesarea.The findings are mainly from the Roman, Byzantine, Muslim and Crusader periods. There are also unique findings from the Hellenistic period and the Jewish settlement in Caesarea.",
    image: "./images/caesarea_antiquity_museum.jpg",
  },
  {
    name: "Umm al-Fahm Art Gallery",
    city: cities.Haifa,
    position: { lat: 32.52325693478524, lng: 35.154157901460785 },
    website: "http://ummelfahemgallery.com/",
    phone: "046315257",
    area: areas.North,
    category: categories.Gallery,
    rating: 4.4,
    price: 40,
    openAtWeekends: true,
    discription:
      "The Arab city of Umm el-Fahem lies in the eastern part of Israel, near the seam line separating the State of Israel from the Palestinian Authority.",
    image: "./images/umm_al-fahm_art_gallery.jpg",
  },
  {
    name: "Ben-Gurion barracks",
    city: cities.SdeBoker,
    position: { lat: 30.873953881591305, lng: 34.788921030316 },
    website: "http://www.ben-gurion.co.il/",
    phone: "086560469",
    area: areas.South,
    category: categories.History,
    rating: 4.6,
    price: 20,
    openAtWeekends: true,
    discription:
      "A person's house indicates his personality, his lifestyle and his worldview. Visitors to the barracks get to know the character of Ben-Gurion as a person and as a leader. In the living shack there is a study room with about 5,000 books in about 9 languages and on various subjects: history, geography, Judaism and more. In the guest room, the symbols of the country are displayed: the map of the Land of Israel, the flag of Israel, a copy of the Declaration of Independence, the state emblem; photos of family members; Objects and souvenirs from the East and various Jewish communities from Israel and the world.",
    image: "./images/ben-gurion_barracks.jpg",
  },
  {
    name: "Menachem Begin Heritage Center",
    city: cities.Jerusalem,
    position: { lat: 31.76932085990338, lng: 35.22542427256326 },
    website: "https://www.begincenter.org.il/",
    phone: "025652020",
    area: areas.Center,
    category: categories.Legacy,
    rating: 4.6,
    price: 0,
    openAtWeekends: true,
    discription:
      "A memorial center for the study of the life and legacy of the former revolutionary soldier and Israeli leader Menachem Begin.",
    image: "./images/menachem_begin_heritage_center.jpg",
  },
  {
    name: "Museum on the Seam",
    city: cities.Jerusalem,
    position: { lat: 31.78617544114428, lng: 35.22677880142157 },
    website: "http://www.mots.org.il/",
    phone: "026281278",
    area: areas.Center,
    category: categories.Art,
    rating: 4.0,
    price: 0,
    openAtWeekends: false,
    discription:
      "A museum of contemporary art housed in a former military post, where exhibits dealing with socio-political issues are presented.",
    image: "./images/museum_on_the_seam.jpg",
  },
  {
    name: "Museum of Italian Jewry",
    city: cities.Jerusalem,
    position: { lat: 31.78617544114428, lng: 35.22677880142157 },
    website: "https://makom.hamoreshet.org.il/landmark/italian-jewish-museum/",
    phone: "None",
    area: areas.Center,
    category: categories.Culture,
    rating: 5.0,
    price: 0,
    openAtWeekends: false,
    discription:
      "The charming museum on Italian Jewry connects you to the unique Jewish culture in Italy. Share with us in the capsule, the Italian Jewish Museum displays items belonging to Jewish life in Italy from the Renaissance to the present day",
    image: "./images/museum_of_italian_jewry.jpg",
  },
  {
    name: "Yad Vashem",
    city: cities.Jerusalem,
    position: { lat: 31.77440336194823, lng: 35.17517305596939 },
    website: "https://www.yadvashem.org/",
    phone: "026443400",
    area: areas.Center,
    category: categories.Holocaust,
    rating: 4.8,
    price: 0,
    openAtWeekends: false,
    discription:
      "Yad Vashem is entrusted with documenting the history of the people of Israel before and during the Holocaust, perpetuating the life story and memory of the millions who perished, and bequeathing the legacy of the Holocaust to future generations. To this end, the institution deals with commemorating and documenting the events of the Holocaust, collecting objects and documents, collecting testimonies about the Holocaust and publishing them, collecting the names of those who perished in the Holocaust and commemorating them, research and education.",
    image: "./images/yad_vashem.jpg",
  },
  {
    name: "Bloomfield Science Museum",
    city: cities.Jerusalem,
    position: { lat: 31.778311109691096, lng: 35.20048841015491 },
    website: "http://mada.org.il/",
    phone: "026544888",
    area: areas.Center,
    category: categories.Science,
    rating: 4.4,
    price: 50,
    openAtWeekends: false,
    discription:
      "A science museum for children with interactive exhibits, workshops and performances.",
    image: "./images/bloomfield_science_museum.jpg",
  },
  {
    name: "David Yellin College of Education",
    city: cities.Jerusalem,
    position: { lat: 31.78193270142588, lng: 35.19068357256296 },
    website: "https://www.dyellin.ac.il/",
    phone: "026558111",
    area: areas.Center,
    category: categories.Art,
    rating: 4.1,
    price: 0,
    openAtWeekends: false,
    discription: "None",
    image: "./images/david_yellin_college_of_education.jpg",
  },
  {
    name: "The New Gallery Artists' Studios Teddy",
    city: cities.Jerusalem,
    position: { lat: 31.750628653546812, lng: 35.1914328 },
    website: "https://www.thenewgalleryteddy.com/",
    phone: "025468892",
    area: areas.Center,
    category: categories.Gallery,
    rating: 4.6,
    price: 20,
    openAtWeekends: false,
    discription:
      "The new gallery - the Teddy artists' workshops is an urban center of the plastic arts department of the Jerusalem Municipality",
    image: "./images/the_new_gallery_artists_studios_teddy.jpg",
  },
  {
    name: "Jerusalem Artists' House",
    city: cities.Jerusalem,
    position: { lat: 31.77991084060443, lng: 35.214449445579824 },
    website: "http://www.art.org.il/",
    phone: "026253653",
    area: areas.Center,
    category: categories.Art,
    rating: 4.5,
    price: 0,
    openAtWeekends: true,
    discription:
      "A non-profit art gallery housed with a restaurant in a historic building, where Israeli and international art is displayed.",
    image: "./images/jerusalem_artists_house.jpg",
  },
  {
    name: "Joe Alon Center",
    city: cities.Lahav,
    position: { lat: 31.77991084060443, lng: 35.214449445579824 },
    website: "http://www.joealon.org.il/",
    phone: "089913394",
    area: areas.South,
    category: categories.Culture,
    rating: 4.2,
    price: 35,
    openAtWeekends: true,
    discription:
      "The experience of visiting the museum consists of a guided tour where visitors will discover objects, pictures and exhibits from the essence of Bedouin life. The visit includes accommodation in a traditional Bedouin tent where the guide demonstrates and talks about making coffee and the custom of hosting guests which is an integral part of the Bedouin life tradition in the Negev.",
    image: "./images/joe_alon_center.jpg",
  },
  {
    name: "Museum of Philistine Culture",
    city: cities.Ashdod,
    position: { lat: 31.798663022631516, lng: 34.640148054333174 },
    website:
      "https://museums.gov.il/he/Museums/pages/ashdod-philistine-culture.aspx",
    phone: "086224799",
    area: areas.South,
    category: categories.Culture,
    rating: 4.4,
    price: 45,
    openAtWeekends: true,
    discription:
      "Exhibitions of pottery and jewelry and an opportunity to participate in a traditional Philistine feast.",
    image: "./images/museum_of_philistine_culture.jpg",
  },
  {
    name: "Beit Yellin",
    city: cities.Jerusalem,
    position: { lat: 31.792667238167155, lng: 35.16404827116387 },
    website:
      "https://shimur.org/sites/%D7%91%D7%99%D7%AA-%D7%99%D7%9C%D7%99%D7%9F-%D7%91%D7%9E%D7%95%D7%A6%D7%90/",
    phone: "025345443",
    area: areas.Center,
    category: categories.Archaeology,
    rating: 4.4,
    price: 20,
    openAtWeekends: true,
    discription:
      "Yehoshua Yelin's private house - a stone building that has undergone extensive renovation and conservation works and is now used as a center for visitors to the origin and the region. The house tells the story of the Jewish pioneering act according to Yelin's personal vision. It also serves as an information center and tutorials for the history of the settlement in and around the town of origin.",
    image: "./images/beit_yellin.jpg",
  },
  {
    name: "Testimony House",
    city: cities.NirGalim,
    position: { lat: 31.82571596544934, lng: 34.68311403023457 },
    website: "http://www.beit-haedut.org.il/",
    phone: "088568476",
    area: areas.Center,
    category: categories.Culture,
    rating: 4.7,
    price: 0,
    openAtWeekends: false,
    discription:
      "At the heart of the pastoral settlement of Nir Galim stands the House of Witnesses, an intimate and special Holocaust museum. The Testimony House was established in the early 1990s. It is the fulfillment of the vision and dream of a group of Holocaust survivors who wanted to tell the Holocaust from a personal and value point of view. The Testimony House is a home for them to this day, they take an active part in it and are an inspiration and a pillar of fire for us before the camp.",
    image: "./images/testimony_house.jpg",
  },
  {
    name: "Tax Museum",
    city: cities.Jerusalem,
    position: { lat: 31.783926199963748, lng: 35.21412910269893 },
    website: "https://www.gov.il/he/departments/Units/tax-museum",
    phone: "026257597",
    area: areas.Center,
    category: categories.History,
    rating: 4.0,
    price: 0,
    openAtWeekends: false,
    discription:
      "The Tax Museum is a small museum, but one of its kind in the museum landscape. Within the walls of the museum is folded the history of the Land of Israel from ancient times to the present day, in the Jewish communities in the diaspora and in the countries of the world, from the aspect of taxes.",
    image: "./images/tax_museum.jpg",
  },
  {
    name: "Museum of Underground Prisoners",
    city: cities.Jerusalem,
    position: { lat: 31.781759926491628, lng: 35.22414261846351 },
    website: "https://museums.mod.gov.il/sites/Jerusalem/Pages/default.aspx",
    phone: "026233166",
    area: areas.Center,
    category: categories.History,
    rating: 4.5,
    price: 20,
    openAtWeekends: false,
    discription:
      "A unique museum dedicated to the Jewish underground in the period before the establishment of the state, housed in a prison from the 19th century.",
    image: "./images/museum_of_underground_prisoners.jpg",
  },
  {
    name: "Agnon House",
    city: cities.Jerusalem,
    position: { lat: 31.74863542342435, lng: 35.22387171533039 },
    website: "http://agnonhouse.org.il/",
    phone: "026716498",
    area: areas.Center,
    category: categories.History,
    rating: 4.3,
    price: 20,
    openAtWeekends: false,
    discription:
      "Agnon's archive was given by his family to the National Schools in Jerusalem and his home in the Talfiot neighborhood was transferred to the Jerusalem Municipality and became a national heritage site open to visitors.",
    image: "./images/agnon_house.jpg",
  },
  {
    name: "Repk Museum",
    city: cities.BatYam,
    position: { lat: 32.018912771286516, lng: 34.75562997255951 },
    website: "http://www.moby.org.il/",
    phone: "036591140",
    area: areas.Center,
    category: categories.History,
    rating: 4.7,
    price: 30,
    openAtWeekends: true,
    discription:
      "The museum presents changing exhibitions of contemporary art as well as works from the museum's collection. Here you can experience works by Israeli and international artists alongside a permanent exhibition featuring the works of local artists. From a discussion and thought about the basic concepts of contemporary artistic activity,",
    image: "./images/repk_museum.jpg",
  },
  {
    name: "Artport",
    city: cities.TelAviv,
    position: { lat: 32.052456643142435, lng: 34.771741352452224 },
    website: "http://www.artport.art/",
    phone: "035182599",
    area: areas.Center,
    category: categories.Art,
    rating: 4.7,
    price: 25,
    openAtWeekends: true,
    discription:
      "The contemporary art center Artport was established in 2011 with the belief that artists and art have a role in generating positive change in society, with the aim of being a home for artists at significant stages in their professional development, and to maintain an environment that enables and supports the creation of new art",
    image: "./images/artport.jpg",
  },
  {
    name: "The municipal art gallery",
    city: cities.Rehovot,
    position: { lat: 31.893089981248014, lng: 34.81275195906968 },
    website: "None",
    phone: "089390390",
    area: areas.Center,
    category: categories.Gallery,
    rating: 4.6,
    price: 0,
    openAtWeekends: false,
    discription: "None",
    image: "./images/the_municipal_art_gallery.jpg",
  },
  {
    name: "Jabotinsky Institute",
    city: cities.TelAviv,
    position: { lat: 31.893089981248014, lng: 34.81275195906968 },
    website: "http://www.jabotinsky.org/",
    phone: "035287320",
    area: areas.Center,
    category: categories.Culture,
    rating: 4.6,
    price: 0,
    openAtWeekends: false,
    discription:
      "The institute was founded in 1937 by Yosef Paamoni (1902-1966), who began with his initiative to preserve the documents and photographs related to the practice and thought of Zeev Jabotinsky and his movement, and subsequently implemented a decision made in 1933 in the central institutions of the movement to establish an archival center, where copies of the publications would be stored of the movement and which will be called the Beit Museum.",
    image: "./images/jabotinsky_institute.jpg",
  },
  {
    name: "Ramla Museum",
    city: cities.Ramla,
    position: { lat: 31.893089981248014, lng: 34.81275195906968 },
    website: "http://en.goramla.com/category/ramla-museum",
    phone: "089292650",
    area: areas.Center,
    category: categories.Culture,
    rating: 4.0,
    price: 0,
    openAtWeekends: false,
    discription:
      "Ramla’s Municipal Museum was opened in 2001 in a historic building erected in 1922 which served Ramla’s municipality in the course of the British Mandatory period.",
    image: "./images/ramla_museum.jpg",
  },
  {
    name: "Babylonian Jewry Heritage Center",
    city: cities.OrYehuda,
    position: { lat: 32.02606808522471, lng: 34.85433334372324 },
    website: "http://www.bjhc.org.il/",
    phone: "035339278",
    area: areas.Center,
    category: categories.Legacy,
    rating: 4.6,
    price: 32,
    openAtWeekends: false,
    discription:
      "The Babel Jewish Heritage Center was established in 1973 with the aim of preserving the history of the Jewish community in Iraq and ensuring that it remains part of the future narrative of the Jewish people. For this purpose, the Center fosters research, preservation and publication activities of the culture and folklore of the Jews of Iraq.",
    image: "./images/babylonian_jewry_heritage_center.jpg",
  },
  {
    name: "Herzliya Arts Center",
    city: cities.Herzliya,
    position: { lat: 32.1750262050877, lng: 34.81740508127466 },
    website: "http://theartistsresidence.org/",
    phone: "099510601",
    area: areas.Center,
    category: categories.Art,
    rating: 4.6,
    price: 32,
    openAtWeekends: true,
    discription:
      "For the artists Herzliya is a creative and frequently changing action space that supports the creation, production, presentation and distribution of contemporary art. To this end, he operates artist residency programs, an exhibition space and work spaces for artists.",
    image: "./images/herzliya_arts_center.jpg",
  },
  {
    name: "Bat Yam Museum of Art",
    city: cities.BatYam,
    position: { lat: 32.02066917076272, lng: 34.756144430231565 },
    website: "http://moby.org.il/",
    phone: "036591140",
    area: areas.Center,
    category: categories.Art,
    rating: 4.4,
    price: 0,
    openAtWeekends: true,
    discription:
      "Bat Yam Museum of Art Stroma 6, Bat Yam 5951509 Directions from Google Maps The Bat Yam Art Museum is located in a park in the heart of the Ramat Yosef neighborhood. The unique round structure of the museum was built in 1961 by architect David Perlstein and is a unique example of the local brutalist building style from the time.",
    image: "./images/bat_yam_museum_of_art.jpg",
  },
  {
    name: "The Yemenite Heritage Center and the Jewish communities of Israel",
    city: cities.Rehovot,
    position: { lat: 31.886954281249906, lng: 34.81568890139744 },
    website: "http://www.bet-moreshet.co.il/",
    phone: "0733946150",
    area: areas.Center,
    category: categories.Culture,
    rating: 4.6,
    price: 0,
    openAtWeekends: true,
    discription:
      "The Center for the Heritage of Yemenite Jewry and Israel Communities includes permanent exhibitions and unique activities for the dissemination and preservation of the heritage of Yemenite Jewry through rare, authentic and unique collections and exhibits.",
    image:
      "./images/the_yemenite_heritage_center_and_the_jewish_communities_of_israel.jpg",
  },
  {
    name: "Heichal Shlomo",
    city: cities.Jerusalem,
    position: { lat: 31.775638571489125, lng: 35.21728860347295 },
    website: "http://www.hechalshlomo.org.il/",
    phone: "025889000",
    area: areas.Center,
    category: categories.Culture,
    rating: 4.6,
    price: 25,
    openAtWeekends: false,
    discription:
      "For the exhibition Subb Sob Gog Ha'ar'at: paper cutouts and poems inspired by Ecclesiastes. Curator: Naomi Shapira",
    image: "./images/heichal_shlomo.jpg",
  },
  {
    name: "Fisher House Museum",
    city: cities.KiryatAta,
    position: { lat: 32.80483302899027, lng: 35.10567692353173 },
    website: "http://www.hechalshlomo.org.il/",
    phone: "025889000",
    area: areas.Center,
    category: categories.Culture,
    rating: 4.4,
    price: 25,
    openAtWeekends: false,
    discription:
      "The museum has a selection of tools that teach about the life of the founders at home and in the field. The archive contains documents, tapes, photos, and memories of the settlement's veterans. In its pedagogical centers, didactic material related to the history of the city: summary works, databases, indoor games, outdoor games, activity sheets, riddles, suggestions for educational projects and videos presenting the history of the city since it was first settled about five thousand years ago.",
    image: "./images/fisher_house_museum.jpg",
  },
  {
    name: "Holon History Museum and Archive",
    city: cities.Holon,
    position: { lat: 32.0203843743, lng: 34.770351859067816 },
    website: "https://museum.holonet.co.il/",
    phone: "035050425",
    area: areas.Center,
    category: categories.Culture,
    rating: 4.2,
    price: 20,
    openAtWeekends: false,
    discription:
      "The museum presents the history of the city of Holon, the city that grew out of the sands, the history of its neighborhoods and residents.",
    image: "./images/holon_history_museum_and_archive.jpg",
  },
  {
    name: "Edmond de Rothschild Foundation Israel",
    city: cities.TelAviv,
    position: { lat: 32.068040946221814, lng: 34.778308081286525 },
    website: "https://edrcenter.com/",
    phone: "046174809",
    area: areas.Center,
    category: categories.Culture,
    rating: 4.6,
    price: 30,
    openAtWeekends: false,
    discription:
      "The Edmond de Rothschild Center from the foundation of the Edmond de Rothschild Foundation works to promote and nurture artists and designers in the first years after completing their higher studies in the fields of art and design in Israel.",
    image: "./images/edmond_de_rothschild_foundation_israel.jpg",
  },
  {
    name: "The Municipal Art Gallery, Beit Gordon",
    city: cities.RishonLeZion,
    position: { lat: 31.963632081225214, lng: 34.807483101396265 },
    website: "http://bl-gallery.co.il/",
    phone: "037572821",
    area: areas.Center,
    category: categories.Gallery,
    rating: 4.6,
    price: 30,
    openAtWeekends: false,
    discription:
      "Laria Urban Art Gallery in Rishon LeZion was established in 2007. The gallery is a landmark of contemporary Israeli art in the urban area. The gallery directs its activities to the public of the city and the surrounding area. Through the exhibitions presented, contemporary and Israeli work in various mediums is examined.",
    image:
      "./images/the_municipal_art_gallery_beit_gordon_london_rishon_lezion.jpg",
  },
  {
    name: "Hebrew Music Museum",
    city: cities.Jerusalem,
    position: { lat: 31.78082786755486, lng: 35.219488816003164 },
    website: "https://hebrewmusicmuseum.com/",
    phone: "025406505",
    area: areas.Center,
    category: categories.Music,
    rating: 4.5,
    price: 60,
    openAtWeekends: false,
    discription:
      "Within the museum lies an exhibition of rare and ancient musical instruments from different historical periods and large diasporas to be explored during an experiential tour with innovative technology. Tours are suitable for all ages and are offered to both individuals and groups. The museum interior has an impressive architectural structure encompassing 7 rooms designed according to different cultural, musical styles.",
    image: "./images/hebrew_music_museum.jpg",
  },
  {
    name: "Yad La-Shiryon Museum",
    city: cities.Letron,
    position: { lat: 31.83844811210262, lng: 34.98017997542742 },
    website: "https://yadlashiryon.com/",
    phone: "086307400",
    area: areas.Center,
    category: categories.IDF,
    rating: 4.6,
    price: 0,
    openAtWeekends: true,
    discription:
      "Yad Lasherion is a commemoration site for the martyrs of the Armored Corps. The site includes a museum of the history of armor and a collection of tanks and armored fighting vehicles. The site is in Letron in the Ayalon Valley, and includes the Taggart fort of the Letron Police that was established by the British Mandate authorities in 1940 and the hill on which it stands.",
    image: "./images/yad_lashiryon_museum.jpg",
  },
];
